### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: FORBIDDEN for url: https://hub.docker.com/v2/repositories/foo/bar/tags/9b74cad2ec14e8113674a75ce8dd9663ea3d262c/

### ISSUE THREAD

**Issue by stephane-klein** [BernardoSilva/docker-hub-cleaner#4]
I have this error:

```
└> python main.py
Going to process docker Hub repository spacefill/external-console and delete all tags older than 30 days.
Traceback (most recent call last):
  File "/Users/stephaneklein/Work/github.com/stephane-klein/docker-hub-cleaner/main.py", line 93, in <module>
    delete_tags_older_than(
  File "/Users/stephaneklein/Work/github.com/stephane-klein/docker-hub-cleaner/main.py", line 68, in delete_tags_older_than
    delete_tag(
  File "/Users/stephaneklein/Work/github.com/stephane-klein/docker-hub-cleaner/main.py", line 53, in delete_tag
    r.raise_for_status()
  File "/Users/stephaneklein/Work/github.com/stephane-klein/docker-hub-cleaner/.pyenv/lib/python3.9/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: FORBIDDEN for url: https://hub.docker.com/v2/repositories/foo/bar/tags/9b74cad2ec14e8113674a75ce8dd9663ea3d262c/
```

I wonder if this is a mistake on my part or if the API has changed and this script is obsolete 🤔

**Comment by stephane-klein** [comment]
Sorry, I made a mistake with the password, the script seems to work perfectly.
